# coding: utf-8

"""
    PlanetHoster API

    | <a href=\"https://apidoc.planethoster.com/fr\">Version Française</a> ## Description The PlanetHoster API allows actions related to domain management and web hosting. ## Details - SSL only: we require that all requests be done over encrypted TLS/SSL connections. - Supported HTTP verbs are GET and POST. If your client does not support all HTTP verbs, you can override the verb with X-Http-Method-Override HTTP header. - Unless otherwise specified in the method documentation, all successful API calls return an **HTTP code 200** with a JSON object. - Errors are returned with an HTTP code 4XX or 5XX, a JSON object with properties \"error\" (an error message) and an \"error_code\" (optional, an integer). - Every string passed to and from the API needs to be UTF-8 encoded. - The API sends ETag headers and supports the If-None-Match header. - Unless otherwise specified, all API methods require authentication with api_user and api_key.  ## Authentication and whitelist 1. In order to be able to contact the API, you must whitelist your IPs. 2. API user and API key are required in the HTTP header.  Whitelisted IP and credentials can be found in the <a href=\"https://my.planethoster.com/domain-reseller\" target=\"_blank\">PlanetHoster Client Area / Reseller section</a>.  <SecurityDefinitions />   # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: tech@support.planethoster.info
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import planethoster
from planethoster.api.email_api import EmailApi  # noqa: E501
from planethoster.rest import ApiException


class TestEmailApi(unittest.TestCase):
    """EmailApi unit test stubs"""

    def setUp(self):
        self.api = EmailApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_n0c_add_email(self):
        """Test case for n0c_add_email

        Add  # noqa: E501
        """
        pass

    def test_n0c_disable_auth(self):
        """Test case for n0c_disable_auth

        Disable Authentication  # noqa: E501
        """
        pass

    def test_n0c_email_auth(self):
        """Test case for n0c_email_auth

        Authentication  # noqa: E501
        """
        pass

    def test_n0c_email_change_password(self):
        """Test case for n0c_email_change_password

        Change password  # noqa: E501
        """
        pass

    def test_n0c_email_change_quota(self):
        """Test case for n0c_email_change_quota

        Change quota  # noqa: E501
        """
        pass

    def test_n0c_emails(self):
        """Test case for n0c_emails

        Emails  # noqa: E501
        """
        pass

    def test_n0c_enable_auth(self):
        """Test case for n0c_enable_auth

        Enable Authentication  # noqa: E501
        """
        pass

    def test_n0c_remove_email(self):
        """Test case for n0c_remove_email

        Remove  # noqa: E501
        """
        pass

    def test_n0c_suspend_emails(self):
        """Test case for n0c_suspend_emails

        Suspend emails  # noqa: E501
        """
        pass

    def test_n0c_unsuspend_emails(self):
        """Test case for n0c_unsuspend_emails

        Unsuspend emails  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
