# coding: utf-8

"""
    PlanetHoster API

    | <a href=\"https://apidoc.planethoster.com/fr\">Version Française</a> ## Description The PlanetHoster API allows actions related to domain management and web hosting. ## Details - SSL only: we require that all requests be done over encrypted TLS/SSL connections. - Supported HTTP verbs are GET and POST. If your client does not support all HTTP verbs, you can override the verb with X-Http-Method-Override HTTP header. - Unless otherwise specified in the method documentation, all successful API calls return an **HTTP code 200** with a JSON object. - Errors are returned with an HTTP code 4XX or 5XX, a JSON object with properties \"error\" (an error message) and an \"error_code\" (optional, an integer). - Every string passed to and from the API needs to be UTF-8 encoded. - The API sends ETag headers and supports the If-None-Match header. - Unless otherwise specified, all API methods require authentication with api_user and api_key.  ## Authentication and whitelist 1. In order to be able to contact the API, you must whitelist your IPs. 2. API user and API key are required in the HTTP header.  Whitelisted IP and credentials can be found in the <a href=\"https://my.planethoster.com/domain-reseller\" target=\"_blank\">PlanetHoster Client Area / Reseller section</a>.  <SecurityDefinitions />   # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: tech@support.planethoster.info
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DomainExternalredirectionBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'domain': 'object',
        'https': 'object',
        'r_type': 'object',
        'destination_domain': 'object',
        'id': 'object'
    }

    attribute_map = {
        'domain': 'domain',
        'https': 'https',
        'r_type': 'rType',
        'destination_domain': 'destinationDomain',
        'id': 'id'
    }

    def __init__(self, domain=None, https=None, r_type=None, destination_domain=None, id=None):  # noqa: E501
        """DomainExternalredirectionBody - a model defined in Swagger"""  # noqa: E501
        self._domain = None
        self._https = None
        self._r_type = None
        self._destination_domain = None
        self._id = None
        self.discriminator = None
        self.domain = domain
        self.https = https
        self.r_type = r_type
        self.destination_domain = destination_domain
        self.id = id

    @property
    def domain(self):
        """Gets the domain of this DomainExternalredirectionBody.  # noqa: E501

        Domain name.  # noqa: E501

        :return: The domain of this DomainExternalredirectionBody.  # noqa: E501
        :rtype: object
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this DomainExternalredirectionBody.

        Domain name.  # noqa: E501

        :param domain: The domain of this DomainExternalredirectionBody.  # noqa: E501
        :type: object
        """
        if domain is None:
            raise ValueError("Invalid value for `domain`, must not be `None`")  # noqa: E501

        self._domain = domain

    @property
    def https(self):
        """Gets the https of this DomainExternalredirectionBody.  # noqa: E501

        Force HTTPS or not.  # noqa: E501

        :return: The https of this DomainExternalredirectionBody.  # noqa: E501
        :rtype: object
        """
        return self._https

    @https.setter
    def https(self, https):
        """Sets the https of this DomainExternalredirectionBody.

        Force HTTPS or not.  # noqa: E501

        :param https: The https of this DomainExternalredirectionBody.  # noqa: E501
        :type: object
        """
        if https is None:
            raise ValueError("Invalid value for `https`, must not be `None`")  # noqa: E501

        self._https = https

    @property
    def r_type(self):
        """Gets the r_type of this DomainExternalredirectionBody.  # noqa: E501


        :return: The r_type of this DomainExternalredirectionBody.  # noqa: E501
        :rtype: object
        """
        return self._r_type

    @r_type.setter
    def r_type(self, r_type):
        """Sets the r_type of this DomainExternalredirectionBody.


        :param r_type: The r_type of this DomainExternalredirectionBody.  # noqa: E501
        :type: object
        """
        if r_type is None:
            raise ValueError("Invalid value for `r_type`, must not be `None`")  # noqa: E501

        self._r_type = r_type

    @property
    def destination_domain(self):
        """Gets the destination_domain of this DomainExternalredirectionBody.  # noqa: E501

        Domain you want to redirect to.  # noqa: E501

        :return: The destination_domain of this DomainExternalredirectionBody.  # noqa: E501
        :rtype: object
        """
        return self._destination_domain

    @destination_domain.setter
    def destination_domain(self, destination_domain):
        """Sets the destination_domain of this DomainExternalredirectionBody.

        Domain you want to redirect to.  # noqa: E501

        :param destination_domain: The destination_domain of this DomainExternalredirectionBody.  # noqa: E501
        :type: object
        """
        if destination_domain is None:
            raise ValueError("Invalid value for `destination_domain`, must not be `None`")  # noqa: E501

        self._destination_domain = destination_domain

    @property
    def id(self):
        """Gets the id of this DomainExternalredirectionBody.  # noqa: E501

        World account ID. Can be found with [/get-accounts](#operation/getAccounts).  # noqa: E501

        :return: The id of this DomainExternalredirectionBody.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DomainExternalredirectionBody.

        World account ID. Can be found with [/get-accounts](#operation/getAccounts).  # noqa: E501

        :param id: The id of this DomainExternalredirectionBody.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainExternalredirectionBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainExternalredirectionBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
