# coding: utf-8

"""
    PlanetHoster API

    | <a href=\"https://apidoc.planethoster.com/fr\">Version Française</a> ## Description The PlanetHoster API allows actions related to domain management and web hosting. ## Details - SSL only: we require that all requests be done over encrypted TLS/SSL connections. - Supported HTTP verbs are GET and POST. If your client does not support all HTTP verbs, you can override the verb with X-Http-Method-Override HTTP header. - Unless otherwise specified in the method documentation, all successful API calls return an **HTTP code 200** with a JSON object. - Errors are returned with an HTTP code 4XX or 5XX, a JSON object with properties \"error\" (an error message) and an \"error_code\" (optional, an integer). - Every string passed to and from the API needs to be UTF-8 encoded. - The API sends ETag headers and supports the If-None-Match header. - Unless otherwise specified, all API methods require authentication with api_user and api_key.  ## Authentication and whitelist 1. In order to be able to contact the API, you must whitelist your IPs. 2. API user and API key are required in the HTTP header.  Whitelisted IP and credentials can be found in the <a href=\"https://my.planethoster.com/domain-reseller\" target=\"_blank\">PlanetHoster Client Area / Reseller section</a>.  <SecurityDefinitions />   # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: tech@support.planethoster.info
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DomainUpdatewafrulesBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'domain': 'object',
        'waf_disabled_rules': 'object',
        'append': 'object',
        'id': 'object'
    }

    attribute_map = {
        'domain': 'domain',
        'waf_disabled_rules': 'wafDisabledRules',
        'append': 'append',
        'id': 'id'
    }

    def __init__(self, domain=None, waf_disabled_rules=None, append=None, id=None):  # noqa: E501
        """DomainUpdatewafrulesBody - a model defined in Swagger"""  # noqa: E501
        self._domain = None
        self._waf_disabled_rules = None
        self._append = None
        self._id = None
        self.discriminator = None
        self.domain = domain
        self.waf_disabled_rules = waf_disabled_rules
        if append is not None:
            self.append = append
        self.id = id

    @property
    def domain(self):
        """Gets the domain of this DomainUpdatewafrulesBody.  # noqa: E501

        Domain name.  # noqa: E501

        :return: The domain of this DomainUpdatewafrulesBody.  # noqa: E501
        :rtype: object
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this DomainUpdatewafrulesBody.

        Domain name.  # noqa: E501

        :param domain: The domain of this DomainUpdatewafrulesBody.  # noqa: E501
        :type: object
        """
        if domain is None:
            raise ValueError("Invalid value for `domain`, must not be `None`")  # noqa: E501

        self._domain = domain

    @property
    def waf_disabled_rules(self):
        """Gets the waf_disabled_rules of this DomainUpdatewafrulesBody.  # noqa: E501

        Rules to disable.  # noqa: E501

        :return: The waf_disabled_rules of this DomainUpdatewafrulesBody.  # noqa: E501
        :rtype: object
        """
        return self._waf_disabled_rules

    @waf_disabled_rules.setter
    def waf_disabled_rules(self, waf_disabled_rules):
        """Sets the waf_disabled_rules of this DomainUpdatewafrulesBody.

        Rules to disable.  # noqa: E501

        :param waf_disabled_rules: The waf_disabled_rules of this DomainUpdatewafrulesBody.  # noqa: E501
        :type: object
        """
        if waf_disabled_rules is None:
            raise ValueError("Invalid value for `waf_disabled_rules`, must not be `None`")  # noqa: E501

        self._waf_disabled_rules = waf_disabled_rules

    @property
    def append(self):
        """Gets the append of this DomainUpdatewafrulesBody.  # noqa: E501

        Append rules to existing disable rules list or reset with new rules list?'  # noqa: E501

        :return: The append of this DomainUpdatewafrulesBody.  # noqa: E501
        :rtype: object
        """
        return self._append

    @append.setter
    def append(self, append):
        """Sets the append of this DomainUpdatewafrulesBody.

        Append rules to existing disable rules list or reset with new rules list?'  # noqa: E501

        :param append: The append of this DomainUpdatewafrulesBody.  # noqa: E501
        :type: object
        """

        self._append = append

    @property
    def id(self):
        """Gets the id of this DomainUpdatewafrulesBody.  # noqa: E501

        World account ID. Can be found with [/get-accounts](#operation/getAccounts).  # noqa: E501

        :return: The id of this DomainUpdatewafrulesBody.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DomainUpdatewafrulesBody.

        World account ID. Can be found with [/get-accounts](#operation/getAccounts).  # noqa: E501

        :param id: The id of this DomainUpdatewafrulesBody.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainUpdatewafrulesBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainUpdatewafrulesBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
