# coding: utf-8

"""
    PlanetHoster API

    | <a href=\"https://apidoc.planethoster.com/fr\">Version Française</a> ## Description The PlanetHoster API allows actions related to domain management and web hosting. ## Details - SSL only: we require that all requests be done over encrypted TLS/SSL connections. - Supported HTTP verbs are GET and POST. If your client does not support all HTTP verbs, you can override the verb with X-Http-Method-Override HTTP header. - Unless otherwise specified in the method documentation, all successful API calls return an **HTTP code 200** with a JSON object. - Errors are returned with an HTTP code 4XX or 5XX, a JSON object with properties \"error\" (an error message) and an \"error_code\" (optional, an integer). - Every string passed to and from the API needs to be UTF-8 encoded. - The API sends ETag headers and supports the If-None-Match header. - Unless otherwise specified, all API methods require authentication with api_user and api_key.  ## Authentication and whitelist 1. In order to be able to contact the API, you must whitelist your IPs. 2. API user and API key are required in the HTTP header.  Whitelisted IP and credentials can be found in the <a href=\"https://my.planethoster.com/domain-reseller\" target=\"_blank\">PlanetHoster Client Area / Reseller section</a>.  <SecurityDefinitions />   # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: tech@support.planethoster.info
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20042Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'all_rules_range': 'object',
        'disabled_rules': 'object',
        'rules': 'object'
    }

    attribute_map = {
        'all_rules_range': 'allRulesRange',
        'disabled_rules': 'disabledRules',
        'rules': 'rules'
    }

    def __init__(self, all_rules_range=None, disabled_rules=None, rules=None):  # noqa: E501
        """InlineResponse20042Data - a model defined in Swagger"""  # noqa: E501
        self._all_rules_range = None
        self._disabled_rules = None
        self._rules = None
        self.discriminator = None
        if all_rules_range is not None:
            self.all_rules_range = all_rules_range
        if disabled_rules is not None:
            self.disabled_rules = disabled_rules
        if rules is not None:
            self.rules = rules

    @property
    def all_rules_range(self):
        """Gets the all_rules_range of this InlineResponse20042Data.  # noqa: E501

        All rules range.  # noqa: E501

        :return: The all_rules_range of this InlineResponse20042Data.  # noqa: E501
        :rtype: object
        """
        return self._all_rules_range

    @all_rules_range.setter
    def all_rules_range(self, all_rules_range):
        """Sets the all_rules_range of this InlineResponse20042Data.

        All rules range.  # noqa: E501

        :param all_rules_range: The all_rules_range of this InlineResponse20042Data.  # noqa: E501
        :type: object
        """

        self._all_rules_range = all_rules_range

    @property
    def disabled_rules(self):
        """Gets the disabled_rules of this InlineResponse20042Data.  # noqa: E501

        Disable rules list.  # noqa: E501

        :return: The disabled_rules of this InlineResponse20042Data.  # noqa: E501
        :rtype: object
        """
        return self._disabled_rules

    @disabled_rules.setter
    def disabled_rules(self, disabled_rules):
        """Sets the disabled_rules of this InlineResponse20042Data.

        Disable rules list.  # noqa: E501

        :param disabled_rules: The disabled_rules of this InlineResponse20042Data.  # noqa: E501
        :type: object
        """

        self._disabled_rules = disabled_rules

    @property
    def rules(self):
        """Gets the rules of this InlineResponse20042Data.  # noqa: E501

        List of all WAF rules.  # noqa: E501

        :return: The rules of this InlineResponse20042Data.  # noqa: E501
        :rtype: object
        """
        return self._rules

    @rules.setter
    def rules(self, rules):
        """Sets the rules of this InlineResponse20042Data.

        List of all WAF rules.  # noqa: E501

        :param rules: The rules of this InlineResponse20042Data.  # noqa: E501
        :type: object
        """

        self._rules = rules

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20042Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20042Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
