# coding: utf-8

"""
    PlanetHoster API

    | <a href=\"https://apidoc.planethoster.com/fr\">Version Française</a> ## Description The PlanetHoster API allows actions related to domain management and web hosting. ## Details - SSL only: we require that all requests be done over encrypted TLS/SSL connections. - Supported HTTP verbs are GET and POST. If your client does not support all HTTP verbs, you can override the verb with X-Http-Method-Override HTTP header. - Unless otherwise specified in the method documentation, all successful API calls return an **HTTP code 200** with a JSON object. - Errors are returned with an HTTP code 4XX or 5XX, a JSON object with properties \"error\" (an error message) and an \"error_code\" (optional, an integer). - Every string passed to and from the API needs to be UTF-8 encoded. - The API sends ETag headers and supports the If-None-Match header. - Unless otherwise specified, all API methods require authentication with api_user and api_key.  ## Authentication and whitelist 1. In order to be able to contact the API, you must whitelist your IPs. 2. API user and API key are required in the HTTP header.  Whitelisted IP and credentials can be found in the <a href=\"https://my.planethoster.com/domain-reseller\" target=\"_blank\">PlanetHoster Client Area / Reseller section</a>.  <SecurityDefinitions />   # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: tech@support.planethoster.info
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserAddsshkeyBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'p_key': 'object',
        'comment': 'object',
        'from_ips': 'object',
        'id': 'object'
    }

    attribute_map = {
        'p_key': 'pKey',
        'comment': 'comment',
        'from_ips': 'fromIps',
        'id': 'id'
    }

    def __init__(self, p_key=None, comment=None, from_ips=None, id=None):  # noqa: E501
        """UserAddsshkeyBody - a model defined in Swagger"""  # noqa: E501
        self._p_key = None
        self._comment = None
        self._from_ips = None
        self._id = None
        self.discriminator = None
        self.p_key = p_key
        if comment is not None:
            self.comment = comment
        if from_ips is not None:
            self.from_ips = from_ips
        self.id = id

    @property
    def p_key(self):
        """Gets the p_key of this UserAddsshkeyBody.  # noqa: E501

        SSH public key.  # noqa: E501

        :return: The p_key of this UserAddsshkeyBody.  # noqa: E501
        :rtype: object
        """
        return self._p_key

    @p_key.setter
    def p_key(self, p_key):
        """Sets the p_key of this UserAddsshkeyBody.

        SSH public key.  # noqa: E501

        :param p_key: The p_key of this UserAddsshkeyBody.  # noqa: E501
        :type: object
        """
        if p_key is None:
            raise ValueError("Invalid value for `p_key`, must not be `None`")  # noqa: E501

        self._p_key = p_key

    @property
    def comment(self):
        """Gets the comment of this UserAddsshkeyBody.  # noqa: E501

        Related comment.  # noqa: E501

        :return: The comment of this UserAddsshkeyBody.  # noqa: E501
        :rtype: object
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this UserAddsshkeyBody.

        Related comment.  # noqa: E501

        :param comment: The comment of this UserAddsshkeyBody.  # noqa: E501
        :type: object
        """

        self._comment = comment

    @property
    def from_ips(self):
        """Gets the from_ips of this UserAddsshkeyBody.  # noqa: E501


        :return: The from_ips of this UserAddsshkeyBody.  # noqa: E501
        :rtype: object
        """
        return self._from_ips

    @from_ips.setter
    def from_ips(self, from_ips):
        """Sets the from_ips of this UserAddsshkeyBody.


        :param from_ips: The from_ips of this UserAddsshkeyBody.  # noqa: E501
        :type: object
        """

        self._from_ips = from_ips

    @property
    def id(self):
        """Gets the id of this UserAddsshkeyBody.  # noqa: E501

        World account ID. Can be found with [/get-accounts](#operation/getAccounts).  # noqa: E501

        :return: The id of this UserAddsshkeyBody.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserAddsshkeyBody.

        World account ID. Can be found with [/get-accounts](#operation/getAccounts).  # noqa: E501

        :param id: The id of this UserAddsshkeyBody.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserAddsshkeyBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserAddsshkeyBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
