# coding: utf-8

"""
    PlanetHoster API

    | <a href=\"https://apidoc.planethoster.com/fr\">Version Française</a> ## Description The PlanetHoster API allows actions related to domain management and web hosting. ## Details - SSL only: we require that all requests be done over encrypted TLS/SSL connections. - Supported HTTP verbs are GET and POST. If your client does not support all HTTP verbs, you can override the verb with X-Http-Method-Override HTTP header. - Unless otherwise specified in the method documentation, all successful API calls return an **HTTP code 200** with a JSON object. - Errors are returned with an HTTP code 4XX or 5XX, a JSON object with properties \"error\" (an error message) and an \"error_code\" (optional, an integer). - Every string passed to and from the API needs to be UTF-8 encoded. - The API sends ETag headers and supports the If-None-Match header. - Unless otherwise specified, all API methods require authentication with api_user and api_key.  ## Authentication and whitelist 1. In order to be able to contact the API, you must whitelist your IPs. 2. API user and API key are required in the HTTP header.  Whitelisted IP and credentials can be found in the <a href=\"https://my.planethoster.com/domain-reseller\" target=\"_blank\">PlanetHoster Client Area / Reseller section</a>.  <SecurityDefinitions />   # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: tech@support.planethoster.info
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WorldapiCreateaccountBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'domain': 'object',
        'country': 'object',
        'cpu': 'object',
        'mem': 'object',
        'io': 'object',
        'ls': 'object'
    }

    attribute_map = {
        'domain': 'domain',
        'country': 'country',
        'cpu': 'cpu',
        'mem': 'mem',
        'io': 'io',
        'ls': 'ls'
    }

    def __init__(self, domain=None, country=None, cpu=None, mem=None, io=None, ls=None):  # noqa: E501
        """WorldapiCreateaccountBody - a model defined in Swagger"""  # noqa: E501
        self._domain = None
        self._country = None
        self._cpu = None
        self._mem = None
        self._io = None
        self._ls = None
        self.discriminator = None
        self.domain = domain
        self.country = country
        if cpu is not None:
            self.cpu = cpu
        if mem is not None:
            self.mem = mem
        if io is not None:
            self.io = io
        if ls is not None:
            self.ls = ls

    @property
    def domain(self):
        """Gets the domain of this WorldapiCreateaccountBody.  # noqa: E501

        World account principal domain.  # noqa: E501

        :return: The domain of this WorldapiCreateaccountBody.  # noqa: E501
        :rtype: object
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this WorldapiCreateaccountBody.

        World account principal domain.  # noqa: E501

        :param domain: The domain of this WorldapiCreateaccountBody.  # noqa: E501
        :type: object
        """
        if domain is None:
            raise ValueError("Invalid value for `domain`, must not be `None`")  # noqa: E501

        self._domain = domain

    @property
    def country(self):
        """Gets the country of this WorldapiCreateaccountBody.  # noqa: E501

        Country code of the requested location.  # noqa: E501

        :return: The country of this WorldapiCreateaccountBody.  # noqa: E501
        :rtype: object
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this WorldapiCreateaccountBody.

        Country code of the requested location.  # noqa: E501

        :param country: The country of this WorldapiCreateaccountBody.  # noqa: E501
        :type: object
        """
        if country is None:
            raise ValueError("Invalid value for `country`, must not be `None`")  # noqa: E501

        self._country = country

    @property
    def cpu(self):
        """Gets the cpu of this WorldapiCreateaccountBody.  # noqa: E501

        Amount of CPU allocated to the account.  # noqa: E501

        :return: The cpu of this WorldapiCreateaccountBody.  # noqa: E501
        :rtype: object
        """
        return self._cpu

    @cpu.setter
    def cpu(self, cpu):
        """Sets the cpu of this WorldapiCreateaccountBody.

        Amount of CPU allocated to the account.  # noqa: E501

        :param cpu: The cpu of this WorldapiCreateaccountBody.  # noqa: E501
        :type: object
        """

        self._cpu = cpu

    @property
    def mem(self):
        """Gets the mem of this WorldapiCreateaccountBody.  # noqa: E501

        Amount of memory allocated to the account (GB).  # noqa: E501

        :return: The mem of this WorldapiCreateaccountBody.  # noqa: E501
        :rtype: object
        """
        return self._mem

    @mem.setter
    def mem(self, mem):
        """Sets the mem of this WorldapiCreateaccountBody.

        Amount of memory allocated to the account (GB).  # noqa: E501

        :param mem: The mem of this WorldapiCreateaccountBody.  # noqa: E501
        :type: object
        """

        self._mem = mem

    @property
    def io(self):
        """Gets the io of this WorldapiCreateaccountBody.  # noqa: E501

        Amount of I/O allocated to the account (MB/s).  # noqa: E501

        :return: The io of this WorldapiCreateaccountBody.  # noqa: E501
        :rtype: object
        """
        return self._io

    @io.setter
    def io(self, io):
        """Sets the io of this WorldapiCreateaccountBody.

        Amount of I/O allocated to the account (MB/s).  # noqa: E501

        :param io: The io of this WorldapiCreateaccountBody.  # noqa: E501
        :type: object
        """

        self._io = io

    @property
    def ls(self):
        """Gets the ls of this WorldapiCreateaccountBody.  # noqa: E501

        Select litespeed server `PRO client only`.  # noqa: E501

        :return: The ls of this WorldapiCreateaccountBody.  # noqa: E501
        :rtype: object
        """
        return self._ls

    @ls.setter
    def ls(self, ls):
        """Sets the ls of this WorldapiCreateaccountBody.

        Select litespeed server `PRO client only`.  # noqa: E501

        :param ls: The ls of this WorldapiCreateaccountBody.  # noqa: E501
        :type: object
        """

        self._ls = ls

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorldapiCreateaccountBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorldapiCreateaccountBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
